import Head from "next/head";
import dynamic from "next/dynamic";

const Spline = dynamic(() => import("@splinetool/react-spline"), {
  ssr: false,
});

export default function Home() {
  return (
    <div className="w-full min-h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed z-50 inset-x-0 w-full flex justify-center items-center text-white">
        <h1 className="text-4xl py-10">Hello, I'm Didem</h1>
      </div>

      <div className="relative">
        <Spline scene="https://draft.spline.design/jXRCpFUaXb8H8Ixq/scene.spline" />
      </div>
    </div>
  );
}
